### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by AnthonyF333** [DeepVAC/SYSZUXface#3]
Error downloading object: dataset/ds/famous/000316/15.jpg (b0b06fc): Smudge error: Error downloading dataset/ds/famous/000316/15.jpg (b0b06fcbaffd1657132e6f0ece51cbc9a6c4e5f49e1be5f0490f49479b33be66): batch response: Fatal error: Server error: https://github.com.cnpmjs.org/DeepVAC/SYSZUXface.git/info/lfs/objects/batch from HTTP 502

**Comment by gemfield** [comment]
May be the downloading was affected by github malfunction yesterday.

**Comment by AnthonyF333** [comment]
Thanks, I will restart to download it, so sad :(
